<script>
    /* <![CDATA[ */

    var FoomanGoogleAnalytics = Class.create();
    FoomanGoogleAnalytics.prototype = {
        initialize: function(settings){
            this.baseUrl = settings.baseUrl;
            this.pageQuery = settings.pageQuery;
            this.classic = settings.classic;
            this.altClassic = settings.altClassic;
            this.universal = settings.universal;
        },
        trackEvent: function(section){

            var urlToTrack = this.baseUrl + '/' + section + this.pageQuery;
            if (this.classic) {
                _gaq.push(['_trackPageview', urlToTrack]);
            }
            if (this.altClassic) {
                _gaq.push(['t2._trackPageview', urlToTrack]);
            }
            if (this.universal) {
                ga('send', 'pageview', urlToTrack);
            }
        }
    }

    var foomanGoogleAnalytics = new FoomanGoogleAnalytics({
            baseUrl: '<?php echo $this->getBasePageName() ?>',
            pageQuery: '<?php echo $this->getPageQuery() ?>',
            classic: '<?php echo $this->getMainAccountId() ?>',
            altClassic: '<?php echo $this->getAlternativeAccountId() ?>',
            universal: '<?php echo $this->isUniversalEnabled() ? $this->getUniversalAccount():'' ?>'
        }
    );

    Accordion.prototype.openSection  = Accordion.prototype.openSection.wrap(function(originalOpenSection, section){
        foomanGoogleAnalytics.trackEvent(section);
        originalOpenSection(section);
    });

    Review.prototype.save  = Review.prototype.save.wrap(function(originalSave){
        foomanGoogleAnalytics.trackEvent('opc-review-placeOrderClicked');
        originalSave();
    });

    /* ]]> */
</script>
