<?php if ($this->shouldIncludeTracking()): ?>
    <?php
    $accountId = $this->getMainAccountId();
    $alternativeAccountId = $this->getAlternativeAccountId();
    $pageName = $this->getPageName();
    $gaUrl = $this->getGaLocation();
    $isSuccess = $this->isSuccessPage();
    ?>
    <!-- BEGIN GOOGLE ANALYTICS CODE -->
    <script>
        /* <![CDATA[ */
        (function () {
            var ga = document.createElement('script');
            ga.type = 'text/javascript';
            ga.async = true;
            ga.src = '<?php echo $gaUrl?>';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(ga, s);
        })();
        var _gaq = _gaq || [];
        <?php echo $this->getPageTrackingCode($accountId, $alternativeAccountId)?>
        <?php //echo $this->getAjaxPageTracking($alternativeAccountId)?>
        <?php echo $this->getOrdersTrackingCode($alternativeAccountId)?>

        <?php if($isSuccess):?>
            <?php echo $this->getCustomerVars($alternativeAccountId)?>
        <?php endif;?>
        /* ]]> */
    </script>
    <!-- END GOOGLE ANALYTICS CODE -->
<?php endif; ?>
