<?php /* @var $this Fooman_GoogleAnalyticsPlus_Block_Universal */?>
<?php if ($this->shouldInclude()): ?>
    <?php $altUniversal = $this->getAlternativeUniversalAccount(); ?>

    <?php if ($this->isGoogleOptimizePageHidingEnabled()): ?>
        <style>.async-hide { opacity: 0 !important} </style>
        <script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
        h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
        (a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
        })(window,document.documentElement,'async-hide','dataLayer',4000,{'<?php echo $this->getGoogleOptimizeContainerId() ?>':true});</script>
    <?php endif; ?>
    <!-- Google Analytics - Part 1/2-->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','<?php echo $this->getAnalyticsLocation(); ?>','ga');

        ga('create', '<?php echo $this->getUniversalAccount(); ?>',<?php echo $this->getUniversalParams(); ?>);
        <?php if ($altUniversal):?>
            ga('create', '<?php echo $altUniversal; ?>',<?php echo $this->getUniversalParams(true); ?>);
        <?php endif;?>

        <?php if($this->getUniversalAnonymise()):?>
            ga('set', 'anonymizeIp', true);
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.set', 'anonymizeIp', true);
            <?php endif;?>
        <?php endif;?>
        <?php if($this->getUniversalForceSSL()):?>
            ga('set', 'forceSSL', true);
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.set', 'forceSSL', true);
            <?php endif;?>
        <?php endif;?>
        <?php if($this->getUniversalDisplayAdvertising()):?>
            ga('require', 'displayfeatures'<?php if($this->getUniversalDisplayAdvertisingCookieName()):?>, undefined, { cookieName: '<?php echo $this->getUniversalDisplayAdvertisingCookieName(); ?>' }<?php endif; ?>);
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.require', 'displayfeatures'<?php if($this->getUniversalDisplayAdvertisingCookieName()):?>, undefined, { cookieName: '<?php echo $this->getUniversalDisplayAdvertisingCookieName(); ?>' }<?php endif; ?>);
            <?php endif;?>
        <?php endif;?>
        <?php if($this->isEnhancedLinkAttrEnabled()):?>
            ga('require', 'linkid');
            <?php if ($altUniversal):?>
                ga('<?php echo Fooman_GoogleAnalyticsPlus_Block_Universal::TRACKER_TWO_NAME?>.require', 'linkid');
            <?php endif;?>
        <?php endif;?>

        <?php if ($this->isGoogleOptimizeEnabled()): ?>
            ga('require', '<?php echo $this->getGoogleOptimizeContainerId() ?>');
        <?php endif; ?>

    </script>
    <!-- End Google Analytics Part 1/2 -->
<?php endif; ?>
